version: "3"


services:
  app:
    build:
      dockerfile: docker/Dockerfile
      
    image: "yegorjke/ping-pong:latest"
    command: "uvicorn pingpong.main:create_app --host 0.0.0.0"
    ports:
      - "8000:8000"
